globals:
  - <script src="https://cdn.polyfill.io/v1/polyfill.min.js"></script>

farm: saucelabs

runner: tape

tests: (npm run build > /dev/null) && browserify 
  -i jsdom 
  -t utilise.filify
  -t tapify 
  dist/resources/lookup-multiple/test.js 
  
watch: 
  - src

browsers:
  - chrome
  - firefox
  - safari
  - ie11
  - ie9